apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: security-gateway
spec:
  to:
    kind: Service
    name: security-gateway
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
